# https://aws.amazon.com/blogs/opensource/network-load-balancer-nginx-ingress-controller-eks
# https://joachim8675309.medium.com/adding-ingress-with-amazon-eks-6c4379803b2
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/
# https://cert-manager.io/docs/usage/ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cortex-ing
spec:
  ingressClassName: nginx
  rules:
    - host: cortexx.dev.itemis.construction
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: cortex-svc
                port:
                  number: 8080
