apiVersion: v1
kind: Service
metadata:
  name: camunda-svc
  namespace: cortex-stage
spec:
  selector:
    app: camunda
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
